# Generated by Django 5.2.8 on 2026-01-05 12:12

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=members.models.getFileName)),
                ('description', models.TextField(max_length=550)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
