# Generated by Django 5.2.8 on 2026-01-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='details',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='description',
            field=models.TextField(max_length=350),
        ),
    ]
