# Generated by Django 5.2.8 on 2026-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_catagory_details_alter_catagory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
